# Generated by Django 3.1.1 on 2020-11-06 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=20)),
                ('discrt', models.CharField(max_length=70)),
                ('pub_date', models.DateField()),
                ('price', models.IntegerField(default=0)),
                ('category', models.CharField(default='Clothing', max_length=10)),
                ('image', models.ImageField(default='', upload_to='shop/images')),
            ],
        ),
    ]
