# Generated by Django 3.1.1 on 2020-11-07 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('phone', models.CharField(default='', max_length=30)),
                ('email', models.CharField(default='', max_length=30)),
                ('query', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
