# Generated by Django 3.1.1 on 2020-11-09 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discrt',
            field=models.CharField(max_length=500),
        ),
    ]
